name: run-e2e-tests
on:
  workflow_dispatch: {}
jobs:
  example-and-package-check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
      - name: "Use NodeJS 16"
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: "Install npm@8.x"
        run: npm i -g npm@next-8
      - name: "Install monorepo packages"
        # This installs all the dependencies of ./packages/*
        # See https://github.com/npm/cli/issues/4475 to see why --foreground-scripts
        run: npm ci --foreground-scripts
      - name: Install CDK example packages
        # Since we are not managing the CDK examples with npm workspaces we install
        # the dependencies in a separate step
        working-directory: ./examples/cdk
        run: npm ci
      - name: "Setup SAM"
        # We use an ad-hoc action so we can specify the SAM CLI version
        uses: aws-actions/setup-sam@v2
        with:
          version: 1.49.0
      - name: Install SAM example packages
        # Since we are not managing the SAM examples with npm workspaces we install
        # the dependencies in a separate step
        working-directory: ./examples/sam
        run: npm ci
      - name: "Test packaging"
        run: |
          npm run lerna-package
          cd examples/cdk
          npm install ../../packages/**/dist/aws-lambda-powertools-*
          npm run test
  package-e2e-tests:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # needed to interact with GitHub's OIDC Token endpoint.
      contents: read
    strategy:
      matrix:
        package: [logger, metrics, tracer]
        version: [12, 14, 16]
      fail-fast: false
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
      - name: "Use NodeJS"
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}
      - name: "Install npm@8.x"
        run: npm i -g npm@next-8
      - name: "Install monorepo packages"
        # This installs all the dependencies of ./packages/*
        # See https://github.com/npm/cli/issues/4475 to see why --foreground-scripts
        run: npm ci --foreground-scripts
      - name: "Configure AWS credentials"
        uses: aws-actions/configure-aws-credentials@v1.6.1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN_TO_ASSUME }}
          aws-region: eu-west-1
      - name: "Run packages integration tests"
        run: |
          RUNTIME=nodejs${{ matrix.version }}x npm run test:e2e -w packages/${{ matrix.package }}
  layer-e2e-tests:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # needed to interact with GitHub's OIDC Token endpoint.
      contents: read
    strategy:
      fail-fast: false
      matrix:
        version: [12, 14, 16]
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
      - name: "Use NodeJS 14"
        uses: actions/setup-node@v3
        with:
          # Always use version 16 as we use TypeScript target es2020
          node-version: 16
      - name: "Install npm@8.x"
        run: npm i -g npm@next-8
      - name: "Configure AWS credentials"
        uses: aws-actions/configure-aws-credentials@v1.6.1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN_TO_ASSUME }}
          aws-region: eu-west-1
      - name: "Run layer integration tests"
        run: |
          npm ci --foreground-scripts
          RUNTIME=nodejs${{ matrix.version }}.x npm run test:e2e
        working-directory: layer-publisher

